### ISSUE TITLE
'Error while burning bootloader. java.lang.NullPointerException' if wrong board selected

### ISSUE THREAD

**Issue by nowatson** [GadgetFactory/DesignLab#13]
If you have selected the wrong board you get the an unhelpful message when trying to run 'Burn Bootloader'.

i.e. if you select 'Papilio FPGA Boards>Papilio Duo FPGA .......' instead of 'Papilio DUO - AVR>Papilio DUO - AVR USB' you will get the following message

Error while burning bootloader.
java.lang.NullPointerException
	at cc.arduino.packages.uploaders.SerialUploader.burnBootloader(SerialUploader.java:339)
	at processing.app.Editor$59.run(Editor.java:2838)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

The tools should give a message reminding the user of the correct physical connections to make and board to select.

**Comment by jackgassett** [comment]
I will try to incorporate a better error message in 1.0.5
