### ISSUE TITLE
'java.io.IOException: Cannot run program papilio-prog.exe' on linux while burning bootloader

### ISSUE THREAD

**Issue by nowatson** [GadgetFactory/DesignLab#14]
I receive a 'java.io.IOException: Cannot run program' error when I try and run burn bootloader on linux.  This fails on linux as the program it is trying to call 'papilio-prog.exe' is 1) not executable and 2) a windows binary.

If I delete the papilio-prog.exe and copy in the linux executable from the parent directory and rename it to papilio-prog.exe, then the bootloader burn works fine.

java.io.IOException: Cannot run program ".xxxxxxxxxxx/DesignLab-1.0.3/hardware/tools/papilio/papilio_loader/bin/papilio-prog.exe": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at processing.app.helpers.ProcessUtils.exec(ProcessUtils.java:13)
	at cc.arduino.packages.Uploader.executeUploadCommand(Uploader.java:105)
	at cc.arduino.packages.uploaders.SerialUploader.burnBootloader(SerialUploader.java:383)
	at processing.app.Editor$59.run(Editor.java:2838)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 20 more
Error while burning bootloader.

**Comment by jackgassett** [comment]
It looks like the build.xml file got hosed when I merged the latest zpuino/arduino changes in. The linux executables are not being swapped out with linux32 or linux64 binaries and the windows versions are being left behind.

**Comment by jackgassett** [comment]
Fixed with commit:
https://github.com/GadgetFactory/DesignLab/commit/20c13e01630a433cdcaab63421deb2fb95af3ef4
