### ISSUE TITLE
Compilation of Basic Arduino Sketch failed with designLab-1.0.3

### ISSUE THREAD

**Issue by quicky2000** [GadgetFactory/DesignLab#19]
I just downloaded DesignLab-1.0.3 and tried to compile a simple sketch ( Arduino basic blink LED) in order to test upload to AVR side but there is an issue inside DesignLab at the end of compilation:

Sketch uses 4,732 bytes (16%) of program storage space. Maximum is 28,672 bytes.
Global variables use 42 bytes (1%) of dynamic memory, leaving 2,518 bytes for local variables. Maximum is 2,560 bytes.
java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:454)
        at java.lang.Integer.parseInt(Integer.java:527)
        at processing.app.Sketch.size(Sketch.java:1721)
        at processing.app.Sketch.build(Sketch.java:1604)
        at processing.app.Sketch.exportApplet(Sketch.java:1625)
        at processing.app.Sketch.exportApplet(Sketch.java:1611)
        at processing.app.Editor$DefaultExportHandler.run(Editor.java:2666)
        at java.lang.Thread.run(Thread.java:745)

**Comment by alvieboy** [comment]
This is already fixed (see commit 0a460ea66dae4d8765ba88c9f48b464ceab55c63).

Jack will release a new DesignLab version soon.

**Comment by quicky2000** [comment]
Good news ! 
Thanks for your reactivity.
I will let Jack close the issue when it will be the good time

**Comment by jackgassett** [comment]
To be included with DesignLab 1.0.4
